import Head from "next/head";

import { NextPage } from "next";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eliaz Bobadilla</title>
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>"
        />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Eliaz Bobadilla</h1>

        <p className={styles.description}>
          Also know as <a href="https://ultirequiem.com/">UltiRequiem</a>
        </p>
      </main>
    </div>
  );
};

export default Home
