import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home({}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eliaz Bobadilla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Eliaz Bobadilla</h1>

        <p className={styles.description}>
          Also know as <a href="https://ultirequiem.com/">UltiRequiem</a>
        </p>
      </main>
    </div>
  );
}
